# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""[P1] Market Sensing Agent for Marketing Value Creator (MVC)."""

import logging
from typing import Any

from google.adk.agents import Agent
from google.adk.apps import App
from google.adk.models import Gemini
from google.adk.tools.google_search_tool import google_search
from google.genai import types

try:
    from app.schemas.deliverables import MarketSensingDeliverable
except ImportError:
    from schemas.deliverables import MarketSensingDeliverable

logger = logging.getLogger(__name__)

MODEL = "gemini-3.5-flash-lite"

MARKET_SENSING_INSTRUCTION = """
You are the expert Market Sensing Agent [P1] for Nova Electronics Corp's Marketing Value Creator (MVC).
Your task is to analyze target markets, extract emerging consumer trends, evaluate competitive dynamics, and assess consumer sentiment.
You have access to Google Search (`google_search`) to ground your analysis with real-time market data, competitor intelligence, and current consumer sentiment.

When presented with campaign requirements (Brand, Product, Objective, Target Audience):
1. Use Google Search to query and verify current market dynamics, competitor campaigns, industry benchmarks, and consumer sentiment signals when relevant.
2. Define the precise Target Market and geographic/demographic scope.
3. Identify at least 3 distinct Consumer Behavior Trends driving demand.
4. Conduct Competitive Analysis on at least 2 primary market competitors, identifying their strengths and vulnerabilities.
5. Synthesize Sentiment Overview, highlighting positive themes, friction points, and an overall sentiment score (-1.0 to 1.0).
6. Recommend at least 3 concrete Strategic Opportunities for the upcoming campaign.

CRITICAL LANGUAGE DIRECTIVE: Output all deliverable textual fields (targetMarket, consumerTrends, competitiveAnalysis, positiveThemes, frictionPoints, strategicOpportunities) strictly in the language of the campaign request (Korean if request or user language is Korean, English if English).

Output your deliverable strictly as a valid JSON object conforming to the required schema.
"""


async def log_market_sensing_grounding(
    callback_context: Any, llm_response: Any
) -> Any | None:
    """Logs Google Search grounding queries performed by the Gemini model.

    Args:
        callback_context: ADK agent invocation callback context.
        llm_response: Response generated by the Gemini model.

    Returns:
        None to pass through the response unmodified.
    """
    del callback_context
    gm = getattr(llm_response, "grounding_metadata", None)
    if gm:
        queries = getattr(gm, "web_search_queries", None)
        if queries:
            logger.info(
                "[Market Sensing Agent] Grounded with Google Search queries: %s",
                queries,
            )
    return None


market_sensing_agent = Agent(
    name="market_sensing_agent",
    model=Gemini(
        model=MODEL,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=MARKET_SENSING_INSTRUCTION,
    tools=[google_search],
    output_schema=MarketSensingDeliverable,
    after_model_callback=log_market_sensing_grounding,
)

app = App(
    root_agent=market_sensing_agent,
    name="market_sensing",
)
