/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service metadata and models */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google OAuth2 login and auto-registration */
        post: operations["loginWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local development mock login */
        post: operations["devLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get currently authenticated user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out and invalidate session cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List campaigns owned by authenticated user */
        get: operations["listUserCampaigns"];
        put?: never;
        /**
         * Start a new multi-agent campaign planning DAG
         * @description Initializes a campaign workflow and initiates P1 (Market Sensing). Returns session details or streams SSE events.
         */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current campaign session state and deliverables */
        get: operations["getCampaignSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{sessionId}/visual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access campaign visual via 307 redirect to V4 Signed URL or in-memory draft */
        get: operations["getCampaignVisual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{sessionId}/draft-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch in-memory draft marketing visual before approval */
        get: operations["getCampaignDraftImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{sessionId}/visual-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ephemeral V4 Signed URL token for campaign visual */
        get: operations["getCampaignVisualToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{sessionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit human-in-the-loop review approval or revision feedback */
        post: operations["approveOrReviseCampaignStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateCampaignRequest: {
            /** @example Nova Electronics Corp */
            brandName: string;
            /** @example Galaxy S27 Ultra */
            productName: string;
            /** @example Black Friday Global Campaign targeting premium tech enthusiasts with AI camera features. */
            campaignObjective: string;
            /** @example Tech-savvy professionals and mobile photographers aged 25-45. */
            targetAudience: string;
            /** @example 1000000 */
            budgetAmount: number;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            /**
             * @example [
             *       "Digital Video",
             *       "Paid Search",
             *       "Social Media",
             *       "Retail Display"
             *     ]
             */
            channels?: string[];
            /**
             * @description Whether to return response as Server-Sent Events (SSE)
             * @default true
             */
            stream: boolean;
        };
        StageApprovalRequest: {
            /**
             * @description 'approve' advances to next stage; 'revise' re-executes current stage with feedback
             * @enum {string}
             */
            action: "approve" | "revise";
            /**
             * @description Marketer text feedback for revision
             * @example Please emphasize trade-in discounts more prominently in the brief and visual prompt.
             */
            feedback?: string;
            /** @default true */
            stream: boolean;
        };
        CampaignSessionResponse: {
            /** @example camp-9f8a3c21 */
            sessionId: string;
            /** @example a8098c1a-f86e-11da-bd1a-00112444be1e */
            userId?: string | null;
            /**
             * @example PAUSED_FOR_REVIEW
             * @enum {string}
             */
            status: "INITIALIZING" | "RUNNING" | "PAUSED_FOR_REVIEW" | "COMPLETED" | "FAILED";
            /**
             * @example MARKET_SENSING
             * @enum {string}
             */
            currentStage: "MARKET_SENSING" | "STRATEGY_BRIEF" | "CREATIVE_CONTENT" | "PERFORMANCE_INSIGHTS" | "COMPLETED";
            /** @example default */
            tenantId?: string;
            channels?: string[];
            /** @example 0 */
            revisionCount?: number;
            brandName: string;
            productName: string;
            campaignObjective?: string;
            budgetAmount?: number;
            currency?: string;
            deliverables?: {
                marketSensing?: components["schemas"]["MarketSensingDeliverable"];
                campaignBrief?: components["schemas"]["CampaignBriefDeliverable"];
                creativeContent?: components["schemas"]["CreativeContentDeliverable"];
                performanceInsights?: components["schemas"]["PerformanceInsightsDeliverable"];
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CampaignStreamEvent: {
            /** @enum {string} */
            event: "stage_started" | "agent_thinking" | "artifact_generated" | "stage_paused_for_review" | "stage_completed" | "campaign_completed" | "error";
            stage: string;
            sessionId?: string;
            data: Record<string, never>;
        };
        MarketSensingDeliverable: {
            targetMarket: string;
            consumerTrends: string[];
            competitiveAnalysis: {
                competitor: string;
                strengths: string[];
                vulnerabilities: string[];
            }[];
            sentimentOverview: {
                positiveThemes: string[];
                frictionPoints: string[];
                overallSentimentScore: number;
            };
            strategicOpportunities: string[];
        };
        CampaignBriefDeliverable: {
            campaignTitle: string;
            coreValueProposition: string;
            targetPersonas: {
                name: string;
                demographics: string;
                primaryNeeds: string[];
                barriers: string[];
            }[];
            messagingPillars: {
                pillar: string;
                keyMessage: string;
                proofPoints: string[];
            }[];
            toneAndVoice: string[];
        };
        CreativeContentDeliverable: {
            visualConceptTitle: string;
            visualPromptUsed: string;
            /** @description GCS URI or HTTP URL of generated marketing image */
            assetUrl: string;
            /** @description Direct gs:// or https:// GCS storage URI of committed asset */
            storageUri?: string | null;
            headlineCopy: string;
            bodyCopy: string;
            callToAction: string;
            /** @default 16:9 */
            aspectRatio: string;
            /** Format: date-time */
            generationTimestamp?: string;
        };
        PerformanceInsightsDeliverable: {
            totalBudget: number;
            currency: string;
            channelAllocations: {
                channel: string;
                allocationAmount: number;
                percentage: number;
                rationale: string;
            }[];
            projectedKpis: {
                estimatedImpressions: number;
                estimatedClicks: number;
                estimatedConversions: number;
                projectedCtr: number;
            };
            expectedRoas: number;
            recommendations: string[];
            /** @description Visual asset URL evaluated for conversion and CTR impact */
            creativeAssetUrl?: string | null;
            /** @description Creative concept summary evaluated during performance modeling */
            visualConceptSummary?: string | null;
        };
        ErrorResponse: {
            error: string;
            message: string;
            traceId: string;
            detail?: Record<string, never>;
        };
        GoogleAuthRequest: {
            /**
             * @description Google OAuth 2.0 OIDC ID token
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
             */
            credential: string;
        };
        DevLoginRequest: {
            /**
             * @default dev-marketer@gmail.com
             * @example dev-marketer@gmail.com
             */
            email: string;
            /**
             * @default Dev Marketer
             * @example Dev Marketer
             */
            name: string;
        };
        UserProfileResponse: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            userId: string;
            /** @example dev-marketer@gmail.com */
            email: string;
            /** @example Dev Marketer */
            name: string;
            /** @example https://lh3.googleusercontent.com/a/default-user */
            picture?: string | null;
            /** @example MARKETER */
            role: string;
            /** @example default */
            tenantId: string;
            /** Format: date-time */
            createdAt: string;
        };
        LogoutResponse: {
            /** @example logged_out */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example healthy */
                        status?: string;
                        /** @example mvc-orchestrator */
                        service?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Marketing Value Creator */
                        name?: string;
                        /** @example 1.0.0 */
                        version?: string;
                        /** @example asia-northeast3 */
                        region?: string;
                        models?: {
                            /** @example gemini-3.1-pro */
                            orchestrator?: string;
                            /** @example gemini-3.5-flash-lite */
                            sub_agents?: string;
                            /** @example gemini-3.1-flash-lite-image */
                            creative_image?: string;
                        };
                        auth?: {
                            googleClientId?: string | null;
                        };
                    };
                };
            };
        };
    };
    loginWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successfully authenticated; sets mvc_session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Invalid Google ID token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    devLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successfully authenticated with mock dev account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    listUserCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of campaigns owned by the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSessionResponse"][];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description Campaign initialized or SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CampaignStreamEvent"];
                    "application/json": components["schemas"]["CampaignSessionResponse"];
                };
            };
            /** @description Invalid request or Model Armor prompt rejection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized / invalid Google OAuth ID token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCampaignSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session state details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSessionResponse"];
                };
            };
            /** @description Campaign session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCampaignVisual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image binary stream (for in-memory draft or streaming fallback) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            /** @description Temporary redirect to Google Cloud Storage V4 Signed URL */
            307: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Visual asset or campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCampaignDraftImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image binary stream of in-memory draft visual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            /** @description No in-memory draft image found for session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCampaignVisualToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ephemeral V4 Signed URL token and expiration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example https://storage.googleapis.com/bucket/path?X-Goog-Signature=... */
                        signedUrl?: string;
                        /** @example 3600 */
                        expiresIn?: number;
                    };
                };
            };
            /** @description Visual asset or campaign not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approveOrReviseCampaignStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageApprovalRequest"];
            };
        };
        responses: {
            /** @description Stage transition processed or SSE stream of next stage execution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["CampaignStreamEvent"];
                    "application/json": components["schemas"]["CampaignSessionResponse"];
                };
            };
            /** @description Invalid stage state or feedback */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
