# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Unit tests for Alembic database migration lifecycle and schema drift."""

import os
import sqlite3
from pathlib import Path

import pytest
from alembic.config import Config

from alembic import command


@pytest.fixture
def alembic_config(tmp_path: Path) -> Config:
    """Fixture providing isolated Alembic configuration with temporary database.

    Args:
        tmp_path: Pytest temporary directory path.

    Returns:
        Configured Alembic Config instance.
    """
    root_dir = Path(__file__).resolve().parent.parent.parent
    ini_path = root_dir / "alembic.ini"
    cfg = Config(str(ini_path))

    temp_db = tmp_path / "test_migration.db"
    # Use standard sqlite URL for sync inspection in alembic command runner
    cfg.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{temp_db}")
    cfg.attributes["db_file"] = str(temp_db)
    return cfg


def test_migration_lifecycle(alembic_config: Config) -> None:
    """Verify upgrade head and downgrade base execution on ephemeral database.

    Args:
        alembic_config: Isolated Alembic configuration fixture.
    """
    db_file = alembic_config.attributes["db_file"]

    # 1. Execute upgrade head
    command.upgrade(alembic_config, "head")

    assert os.path.exists(db_file)
    with sqlite3.connect(db_file) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;"
        )
        tables = {row[0] for row in cursor.fetchall()}

    expected_tables = {
        "alembic_version",
        "users",
        "user_sessions",
        "orchestrator_sessions",
    }
    assert expected_tables.issubset(tables)

    # 2. Execute downgrade base
    command.downgrade(alembic_config, "base")

    with sqlite3.connect(db_file) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;"
        )
        post_downgrade_tables = {row[0] for row in cursor.fetchall()}

    assert "users" not in post_downgrade_tables
    assert "user_sessions" not in post_downgrade_tables
    assert "orchestrator_sessions" not in post_downgrade_tables


def test_schema_drift_check(alembic_config: Config) -> None:
    """Verify alembic check detects zero schema drift against target models.

    Args:
        alembic_config: Isolated Alembic configuration fixture.
    """
    command.upgrade(alembic_config, "head")
    # command.check raises AutogenerateDiffsDetected or CommandError if drift
    command.check(alembic_config)


def test_upgrade_with_pre_existing_tables(
    alembic_config: Config, tmp_path: Path
) -> None:
    """Verify upgrade head succeeds without error when tables already exist.

    Args:
        alembic_config: Isolated Alembic configuration fixture.
        tmp_path: Pytest temporary directory path.
    """
    db_file = tmp_path / "test_preexisting.db"
    alembic_config.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{db_file}")
    alembic_config.attributes["db_file"] = str(db_file)

    # Pre-create tables directly (simulating pre-existing DB before Alembic)
    with sqlite3.connect(db_file) as conn:
        conn.execute(
            "CREATE TABLE users (user_id VARCHAR(64) PRIMARY KEY, "
            "google_sub VARCHAR(128) UNIQUE, email VARCHAR(255) UNIQUE, "
            "name VARCHAR(128), picture VARCHAR(512), role VARCHAR(32), "
            "tenant_id VARCHAR(64), is_active BOOLEAN, created_at DATETIME, "
            "updated_at DATETIME, last_login_at DATETIME);"
        )
        conn.execute(
            "CREATE TABLE user_sessions (session_token VARCHAR(128) PRIMARY KEY, "
            "user_id VARCHAR(64), expires_at DATETIME, created_at DATETIME, "
            "last_accessed_at DATETIME, ip_address VARCHAR(64), user_agent VARCHAR(256));"
        )
        conn.execute(
            "CREATE TABLE orchestrator_sessions (session_id VARCHAR(64) PRIMARY KEY, "
            "user_id VARCHAR(64), tenant_id VARCHAR(64), status VARCHAR(32), "
            "current_stage VARCHAR(32), brand_name VARCHAR(128), product_name VARCHAR(128), "
            "campaign_objective TEXT, budget_amount FLOAT, currency VARCHAR(16), "
            "channels JSON, deliverables JSON, revision_count INTEGER, "
            "created_at DATETIME, updated_at DATETIME);"
        )

    # Running upgrade head should detect existing tables and succeed without error
    command.upgrade(alembic_config, "head")

    # Verify alembic_version was created and stamped to current revision
    with sqlite3.connect(db_file) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT version_num FROM alembic_version;")
        version = cursor.fetchone()[0]
        assert version == "0001_initial_schema"
